// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

import (
	"fmt"
)

//int sum(int a, int b) { return a + b; }
import _ "unsafe"

func main() {
	fmt.Println(( /*line :11:14*/_Cfunc_sum /*line :11:18*/)(1, 1))
}
